---
- name: Install and configure cuda
  hosts: all
  become: yes

  vars:
    USERNAME: cloudgenius

  tasks:

    - name: install nvidia driver and cuda toolkit
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - nvidia-driver-570-server
        - nvidia-cuda-toolkit
        - cmake
        - build-essential
