---
- name: Install Nvidia Container Toolkit
  hosts: all
  become: yes
  tasks:
    - name: Add Nvidia GPG key
      apt_key:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        keyring: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
        state: present

    - name: Change permission
      file:
        path: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
        state: file
        owner: root
        group: root
        mode: a+r

    - name: Add Nvidia container repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH)/
        state: present

# deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /
# #deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/experimental/deb/$(ARCH) /


    # - name: Add Nvidia container repository
    #   shell: |
    #     curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    #       sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    #       sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
    #   args:
    #     creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

    # - name: Enable experimental repositories (if commented)
    #   shell: sed -i -e '/experimental/ s/^#//g' /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Install nvidia-container-toolkit
      apt:
        name: nvidia-container-toolkit
        state: present
        update_cache: yes
