# https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
---
- name: Install Nvidia Container Toolkit
  hosts: all
  become: yes
  tasks:
    - name: Add Nvidia GPG key
      apt_key:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        keyring: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
        state: present

    - name: Change permission
      file:
        path: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
        state: file
        owner: root
        group: root
        mode: a+r

    # - name: Add Nvidia container repository
    #   apt_repository:
    #     repo: deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /
    #     state: present

    - name: Add Nvidia container repository
      shell: |
        curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
          sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
          sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      args:
        creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

    # - name: Enable experimental repositories (if commented)
    #   shell: sed -i -e '/experimental/ s/^#//g' /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Install nvidia-container-toolkit
      apt:
        name: nvidia-container-toolkit
        state: present
        update_cache: yes

    - name: Install nvidia-docker2
      apt:
        name: nvidia-docker2
        state: present
        update_cache: yes

    - name: configure nvidia-ctk runtime
      command: sudo nvidia-ctk runtime configure --runtime=docker

    - name: Ensure docker is restarted and enabled
      systemd:
        name: docker
        enabled: yes
        state: restarted

# docker run --rm --gpus all nvidia/cuda:12.6.3-cudnn-runtime-ubuntu24.04 nvidia-smi
# docker run --rm --gpus all nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04 nvidia-smi
# https://github.com/iot-salzburg/gpu-jupyter
# https://cschranz.medium.com/set-up-your-own-gpu-based-jupyterlab-e0d45fcacf43