---
- name: Install and configure Resilio Sync on Ubuntu
  hosts: all
  become: yes

  vars:
    USERNAME: cloudgenius

  tasks:

      # wget -qO- https://linux-packages.resilio.com/resilio-sync/key.asc | sudo tee /etc/apt/trusted.gpg.d/resilio-sync.asc > /dev/null 2>&1

    - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: https://linux-packages.resilio.com/resilio-sync/key.asc
        state: present

    - name: Add Resilio Sync repository
      apt_repository:
        repo: "deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free"
        state: present
        filename: "resilio-sync"

    - name: Install Resilio Sync package
      apt:
        name: resilio-sync
        state: present
        update_cache: yes

    - name: install git and vim packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - vim
        - git

    # file module will create a directory if missing
    - name: Create resilio-sync.service.d directory
      file:
        path: /etc/systemd/system/resilio-sync.service.d/
        state: directory
        owner: root
        group: root
        mode: 0755


    # template module will create a file
    - name: Copy resilio-sync.service drop-in
      template:
        src: resilio-sync.service.j2
        dest: /etc/systemd/system/resilio-sync.service.d/override.conf
        owner: root
        group: root
        mode: 0644
      notify: reload systemd # Don't forget to do `systemctl daemon-reload`!

    - name: Create /var/lib/resilio-sync/ if it does not exist
      ansible.builtin.file:
        path: /var/lib/resilio-sync/
        state: directory
        owner: root
        group: root
        mode: 0755
        
    - name: Copy Resilio Sync license file
      ansible.builtin.get_url:
        url: https://download.i.cloudgenius.app/Resilio/Sync_Home_23515.btskey # ./Sync_Home_23515.btskey  # Adjust this path to your license file location
        dest: /var/lib/resilio-sync/.sync_license
        owner: root
        group: root
        mode: '0644'

    - name: Ensure Resilio Sync is restarted and enabled
      systemd:
        name: resilio-sync
        enabled: yes
        state: restarted

  handlers:
    - name: reload systemd
      become: yes
      # command: systemctl daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true
